minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - pnpm

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild

overrides:
  fast-xml-parser@<=5.3.3: '>=5.3.4'
  seroval@<1.4.1: '>=1.4.1'
  '@eslint/js': "^9"
  'eslint': "^9"
